//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Runnnnnnnnnn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int id { get; set; }
        public string email { get; set; }
        public string startDate { get; set; }
        public string endDate { get; set; }
        public string carType { get; set; }
        public string car { get; set; }
    }
}
